### ISSUE TITLE
Uncaught TypeError: tdweb is not a constructor when using @types/tdweb

### ISSUE THREAD

**Issue by likidu** [gennadypolakov/svelte-tdweb-starter#1]
Hi,

First of all, thank for bring this starter template for using `tdweb` and `svelte`, really nice.

I am trying to adding `@types/tdweb` npm pack in order to get some typed support for the program. And I modified the 

https://github.com/gennadypolakov/svelte-tdweb-starter/blob/master/src/Tg/Tg.ts#L1

to

`import TdClient from 'tdweb';`

But then I got this error:

`Uncaught TypeError: tdweb is not a constructor`.

Any hint will be helpful. Thanks!

**Comment by gennadypolakov** [comment]
i couldn't get this error after installing @types/tdlib
but i fixed some bugs
maybe after a clean installation the bug will disappear
